name: cobble
description: A Pebble companion app

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.1+1

environment:
  sdk: '>=2.19.0'
  flutter: '3.7.12'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  webview_flutter: ^4.4.2
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.0
  intl: ^0.17.0
  states_rebuilder: ^6.4.0
  path_provider: ^2.1.0
  sqflite: ^2.2.0
  package_info_plus: ^4.2.0
  state_notifier: ^1.0.0
  hooks_riverpod: ^2.0.0
  flutter_hooks: ^0.20.5
  device_calendar:
    git:
      url: https://github.com/builttoroam/device_calendar.git
      ref: b21ffc1 # 4.3.2 + AGP 8.0 compat
  uuid_type: ^2.0.0
  path: ^1.8.0
  json_annotation: ^4.6.0
  copy_with_extension: ^5.0.0
  flutter_local_notifications: ^17.1.2
  stream_transform: ^2.1.0
  flutter_svg: ^2.0.0
  flutter_svg_provider: ^1.0.4
  golden_toolkit: ^0.15.0
  rxdart: 0.27.7
  share_plus: ^7.2.2
  network_info_plus: ^5.0.3
  file: ^6.1.4

  collection: ^1.17.0
  flutter_secure_storage: ^8.0.0
  crypto: ^3.0.3
  cached_network_image: ^3.0.0
  device_info_plus: ^9.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  pigeon: ^9.2.4
  build_runner: ^2.3.0
  json_serializable: ^6.5.0
  copy_with_extension_gen: ^5.0.0
  sqflite_common_ffi: ^2.2.0
  mockito: ^5.3.0
  source_gen: ^1.2.1
  recase: ^4.0.0
  flutter_lints: ^2.0.0

flutter_icons:
  ios: true
  image_path: "images/launcher.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lang/
    - images/

  fonts:
    - family:  RebbleIcons
      fonts:
        - asset: fonts/RebbleIcons.ttf
    - family:  PebbleWatchIcons
      fonts:
        - asset: fonts/PebbleWatchIcons.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
