name: cobble
description: A Pebble companion app

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  webview_flutter: ^0.3.21
  shared_preferences: ^0.5.7+2
  url_launcher: ^5.4.7
  intl: ^0.16.1
  states_rebuilder: ^2.2.0
  path_provider: ^1.6.11
  sqflite: ^1.3.1
  package_info: ^0.4.3+2
  state_notifier: ^0.6.0
  hooks_riverpod: ^0.12.0
  flutter_hooks: 0.14.1
  # We are using custom build of device_calendar with enhancements needed for Cobble app
  # pending PRs:
  # - https://github.com/builttoroam/device_calendar/pull/275
  # - https://github.com/builttoroam/device_calendar/pull/256
  # - https://github.com/builttoroam/device_calendar/pull/276
  device_calendar:
    git:
      url: https://github.com/matejdro/device_calendar.git
      ref: 8ec96c83d482cada5a910cd6b98505eb35027400
  uuid_type: ^1.0.0
  path: ^1.7.0
  json_annotation: ^3.0.0
  copy_with_extension: ^1.4.0
  flutter_local_notifications: ^3.0.2


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_launcher_icons: "^0.7.5"
  flutter_test:
    sdk: flutter
  # Fixed build of pigeon is needed for async native -> flutter calls.
  # PR pending: https://github.com/flutter/packages/pull/254
  pigeon:
    git:
      url: https://github.com/matejdro/flutter-packages.git
      ref: 5d51f8add9f2162487465c99a64e5cd6d4b563f6
      path: packages/pigeon
  build_runner: ^1.0.0
  json_serializable: ^3.2.0
  copy_with_extension_gen: ^1.4.0
  sqflite_common_ffi: ^1.1.1

flutter_icons:
  ios: true
  image_path: "images/launcher.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lang/en.json
    - lang/es.json
    - images/rebble.png
    - images/app_large.png
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
      - family:  RebbleIcons
        fonts:
          - asset: fonts/RebbleIcons.ttf
      - family:  PebbleWatchIcons
        fonts:
          - asset: fonts/PebbleWatchIcons.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
