[versions]
activityCompose = "1.9.3"
android-minSdk = "29"
android-targetSdk = "34"
androidxLifecycle = "2.8.2"
androidxVersion = "1.15.0"
ble = "1.0.16"
coroutinesVersion = "1.8.1"
daggerVersion = "2.51.1"
desugar = "2.0.4"
gradle = "8.7.2"
koinVersion = "4.0.0"
kotlin = "2.1.0-RC"
kotlinxDatetime = "0.6.0"
kotlinxSerializationJson = "1.7.1"
ksp = "2.1.0-RC-1.0.27"
libpebblecommonVersion = "0.1.27"
errorproneVersion = "2.26.1"
logbackAndroid = "3.0.0"
mockk = "1.13.11"
okio = "3.9.0"
rruleVersion = "1.0.3"
slf4jApi = "2.0.9"
spotbugsVersion = "4.8.6"
atomicfu = "0.25.0"
securityCrypto = "1.1.0-alpha06"

protoliteWellKnownTypes = "18.0.0"
room = "2.7.0-alpha11"
room-sqlite = "2.5.0-alpha11"
datastore = "1.1.1"
androidxTest = "1.7.2"
timberVersion = "5.0.1"
uuidVersion = "0.8.4"
compose-lib = "1.7.0"
compose-nav = "2.8.0-alpha08"
compose-viewmodel = "2.8.0"
reorderable = "2.3.3"

appcompat = "1.7.0"
ktorVersion = "2.3.12"
workManagerVersion = "2.10.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
material = "1.12.0"
detekt = "1.23.8"

[plugins]
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }

androidx-room = { id = "androidx.room", version.ref = "room" }
android-kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "gradle" }
android-application = { id = "com.android.application", version.ref = "gradle" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "compose-lib" }
jetbrains-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrains-kotlinx-atomicfu = { id = "org.jetbrains.kotlinx.atomicfu", version.ref = "atomicfu" }

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidxVersion" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-service = { module = "androidx.lifecycle:lifecycle-service", version.ref = "androidxLifecycle" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidxTest" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidxTest" }
androidx-test-monitor = { module = "androidx.test:monitor", version.ref = "androidxTest" }
androidx-security-crypto-ktx = { module = "androidx.security:security-crypto-ktx", version.ref = "securityCrypto" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workManagerVersion" }
ble-core = { module = "no.nordicsemi.android.kotlin.ble:core", version.ref = "ble" }
ble-server = { module = "no.nordicsemi.android.kotlin.ble:server", version.ref = "ble" }
dagger = { module = "com.google.dagger:dagger", version.ref = "daggerVersion" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "daggerVersion" }
desugar = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
kgp = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
errorprone-annotations = { module = "com.google.errorprone:error_prone_annotations", version.ref = "errorproneVersion" }
logback-android = { module = "com.github.tony19:logback-android", version.ref = "logbackAndroid" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
rrule = { module = "com.github.PhilJay:RRule", version.ref = "rruleVersion" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4jApi" }
spotbugs-annotations = { module = "com.github.spotbugs:spotbugs-annotations", version.ref = "spotbugsVersion" }

androidx-sqlite = { module = "androidx.sqlite:sqlite", version.ref = "room-sqlite" }
androidx-sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "room-sqlite" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koinVersion" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koinVersion" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koinVersion" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koinVersion" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutinesVersion" }
kotlinx-coroutines-debug = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-debug", version.ref = "coroutinesVersion" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutinesVersion" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutinesVersion" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinxSerializationJson" }
libpebblecommon = { module = "io.rebble.libpebblecommon:libpebblecommon", version.ref = "libpebblecommonVersion" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timberVersion" }
uuid = { module = "com.benasher44:uuid", version.ref = "uuidVersion" }
protolite-wellknowntypes = { module = "com.google.firebase:protolite-well-known-types", version.ref = "protoliteWellKnownTypes" }
jetbrains-kotlinx-atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "atomicfu" }

ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktorVersion" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktorVersion" }
ktor-client-contentnegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktorVersion" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktorVersion" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktorVersion" }

compose-navigation = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "compose-nav" }
compose-viewmodel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "compose-viewmodel" }
compose-components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose-lib" }
compose-components-reorderable = { module = "sh.calvin.reorderable:reorderable", version.ref = "reorderable" }

androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }